"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.knowledgeEntityLinkQueries = exports.knowledgeEntityQueries = exports.blockTopicAssignmentQueries = exports.confusionPatternQueries = exports.topicQuizQueries = exports.intakeQuizQueries = exports.getDatabaseStatus = exports.devSettingsQueries = exports.settingsQueries = exports.searchQueries = exports.seedReferenceRangesFromLocalFile = exports.invalidateReferenceRangeCache = exports.getReferenceRangeCache = exports.referenceRangeQueries = exports.seedMedicalAcronymsFromLocalFile = exports.invalidateAcronymCache = exports.getAcronymCache = exports.medicalAcronymQueries = exports.parseSmartViewRow = exports.seedSystemSmartViews = exports.smartViewQueries = exports.parseNotebookLinkRow = exports.notebookLinkQueries = exports.parseNotebookBlockRow = exports.notebookBlockQueries = exports.parseNotebookTopicPageRow = exports.getNotebookTopicsWithStats = exports.notebookTopicPageQueries = exports.parseCanonicalTopicRow = exports.canonicalTopicQueries = exports.connectionQueries = exports.parseQuickCaptureRow = exports.parseSourceItemRow = exports.getBoardRelevanceForTopic = exports.quickCaptureQueries = exports.sourceItemQueries = exports.parseReviewLogRow = exports.reviewLogQueries = exports.parseNoteRow = exports.noteQueries = exports.parseCardRow = exports.cardQueries = exports.setSchemaVersion = exports.getSchemaVersion = exports.tableExists = exports.columnExists = exports.getDbPath = exports.closeDatabase = exports.getDatabase = exports.initDatabase = void 0;
exports.isEntityReadyForForging = exports.getExpectedCardCount = exports.generateCardsForEntity = exports.simulatorAttemptQueries = exports.practiceBankQueries = exports.FAILURE_ATTRIBUTION_OPTIONS = exports.GOLDEN_TICKET_FIELDS = void 0;
var client_1 = require("./database/client");
Object.defineProperty(exports, "initDatabase", { enumerable: true, get: function () { return client_1.initDatabase; } });
Object.defineProperty(exports, "getDatabase", { enumerable: true, get: function () { return client_1.getDatabase; } });
Object.defineProperty(exports, "closeDatabase", { enumerable: true, get: function () { return client_1.closeDatabase; } });
Object.defineProperty(exports, "getDbPath", { enumerable: true, get: function () { return client_1.getDbPath; } });
Object.defineProperty(exports, "columnExists", { enumerable: true, get: function () { return client_1.columnExists; } });
Object.defineProperty(exports, "tableExists", { enumerable: true, get: function () { return client_1.tableExists; } });
Object.defineProperty(exports, "getSchemaVersion", { enumerable: true, get: function () { return client_1.getSchemaVersion; } });
Object.defineProperty(exports, "setSchemaVersion", { enumerable: true, get: function () { return client_1.setSchemaVersion; } });
var cards_1 = require("./database/cards");
Object.defineProperty(exports, "cardQueries", { enumerable: true, get: function () { return cards_1.cardQueries; } });
Object.defineProperty(exports, "parseCardRow", { enumerable: true, get: function () { return cards_1.parseCardRow; } });
var notes_1 = require("./database/notes");
Object.defineProperty(exports, "noteQueries", { enumerable: true, get: function () { return notes_1.noteQueries; } });
Object.defineProperty(exports, "parseNoteRow", { enumerable: true, get: function () { return notes_1.parseNoteRow; } });
var review_logs_1 = require("./database/review-logs");
Object.defineProperty(exports, "reviewLogQueries", { enumerable: true, get: function () { return review_logs_1.reviewLogQueries; } });
Object.defineProperty(exports, "parseReviewLogRow", { enumerable: true, get: function () { return review_logs_1.parseReviewLogRow; } });
var source_items_1 = require("./database/source-items");
Object.defineProperty(exports, "sourceItemQueries", { enumerable: true, get: function () { return source_items_1.sourceItemQueries; } });
Object.defineProperty(exports, "quickCaptureQueries", { enumerable: true, get: function () { return source_items_1.quickCaptureQueries; } });
Object.defineProperty(exports, "getBoardRelevanceForTopic", { enumerable: true, get: function () { return source_items_1.getBoardRelevanceForTopic; } });
Object.defineProperty(exports, "parseSourceItemRow", { enumerable: true, get: function () { return source_items_1.parseSourceItemRow; } });
Object.defineProperty(exports, "parseQuickCaptureRow", { enumerable: true, get: function () { return source_items_1.parseQuickCaptureRow; } });
var connections_1 = require("./database/connections");
Object.defineProperty(exports, "connectionQueries", { enumerable: true, get: function () { return connections_1.connectionQueries; } });
var canonical_topics_1 = require("./database/canonical-topics");
Object.defineProperty(exports, "canonicalTopicQueries", { enumerable: true, get: function () { return canonical_topics_1.canonicalTopicQueries; } });
Object.defineProperty(exports, "parseCanonicalTopicRow", { enumerable: true, get: function () { return canonical_topics_1.parseCanonicalTopicRow; } });
var notebook_topic_pages_1 = require("./database/notebook-topic-pages");
Object.defineProperty(exports, "notebookTopicPageQueries", { enumerable: true, get: function () { return notebook_topic_pages_1.notebookTopicPageQueries; } });
Object.defineProperty(exports, "getNotebookTopicsWithStats", { enumerable: true, get: function () { return notebook_topic_pages_1.getTopicsWithStats; } });
Object.defineProperty(exports, "parseNotebookTopicPageRow", { enumerable: true, get: function () { return notebook_topic_pages_1.parseNotebookTopicPageRow; } });
var notebook_blocks_1 = require("./database/notebook-blocks");
Object.defineProperty(exports, "notebookBlockQueries", { enumerable: true, get: function () { return notebook_blocks_1.notebookBlockQueries; } });
Object.defineProperty(exports, "parseNotebookBlockRow", { enumerable: true, get: function () { return notebook_blocks_1.parseNotebookBlockRow; } });
var notebook_links_1 = require("./database/notebook-links");
Object.defineProperty(exports, "notebookLinkQueries", { enumerable: true, get: function () { return notebook_links_1.notebookLinkQueries; } });
Object.defineProperty(exports, "parseNotebookLinkRow", { enumerable: true, get: function () { return notebook_links_1.parseNotebookLinkRow; } });
var smart_views_1 = require("./database/smart-views");
Object.defineProperty(exports, "smartViewQueries", { enumerable: true, get: function () { return smart_views_1.smartViewQueries; } });
Object.defineProperty(exports, "seedSystemSmartViews", { enumerable: true, get: function () { return smart_views_1.seedSystemSmartViews; } });
Object.defineProperty(exports, "parseSmartViewRow", { enumerable: true, get: function () { return smart_views_1.parseSmartViewRow; } });
var medical_acronyms_1 = require("./database/medical-acronyms");
Object.defineProperty(exports, "medicalAcronymQueries", { enumerable: true, get: function () { return medical_acronyms_1.medicalAcronymQueries; } });
Object.defineProperty(exports, "getAcronymCache", { enumerable: true, get: function () { return medical_acronyms_1.getAcronymCache; } });
Object.defineProperty(exports, "invalidateAcronymCache", { enumerable: true, get: function () { return medical_acronyms_1.invalidateAcronymCache; } });
Object.defineProperty(exports, "seedMedicalAcronymsFromLocalFile", { enumerable: true, get: function () { return medical_acronyms_1.seedMedicalAcronymsFromLocalFile; } });
var reference_ranges_1 = require("./database/reference-ranges");
Object.defineProperty(exports, "referenceRangeQueries", { enumerable: true, get: function () { return reference_ranges_1.referenceRangeQueries; } });
Object.defineProperty(exports, "getReferenceRangeCache", { enumerable: true, get: function () { return reference_ranges_1.getReferenceRangeCache; } });
Object.defineProperty(exports, "invalidateReferenceRangeCache", { enumerable: true, get: function () { return reference_ranges_1.invalidateReferenceRangeCache; } });
Object.defineProperty(exports, "seedReferenceRangesFromLocalFile", { enumerable: true, get: function () { return reference_ranges_1.seedReferenceRangesFromLocalFile; } });
var search_1 = require("./database/search");
Object.defineProperty(exports, "searchQueries", { enumerable: true, get: function () { return search_1.searchQueries; } });
var settings_1 = require("./database/settings");
Object.defineProperty(exports, "settingsQueries", { enumerable: true, get: function () { return settings_1.settingsQueries; } });
var dev_settings_1 = require("./database/dev-settings");
Object.defineProperty(exports, "devSettingsQueries", { enumerable: true, get: function () { return dev_settings_1.devSettingsQueries; } });
var status_1 = require("./database/status");
Object.defineProperty(exports, "getDatabaseStatus", { enumerable: true, get: function () { return status_1.getDatabaseStatus; } });
// Notebook v2 query modules (v24)
var intake_quiz_1 = require("./database/intake-quiz");
Object.defineProperty(exports, "intakeQuizQueries", { enumerable: true, get: function () { return intake_quiz_1.intakeQuizQueries; } });
var topic_quiz_1 = require("./database/topic-quiz");
Object.defineProperty(exports, "topicQuizQueries", { enumerable: true, get: function () { return topic_quiz_1.topicQuizQueries; } });
var confusion_patterns_1 = require("./database/confusion-patterns");
Object.defineProperty(exports, "confusionPatternQueries", { enumerable: true, get: function () { return confusion_patterns_1.confusionPatternQueries; } });
var block_topic_assignments_1 = require("./database/block-topic-assignments");
Object.defineProperty(exports, "blockTopicAssignmentQueries", { enumerable: true, get: function () { return block_topic_assignments_1.blockTopicAssignmentQueries; } });
// Medical Knowledge Archetypes (v26)
var knowledge_entities_1 = require("./database/knowledge-entities");
Object.defineProperty(exports, "knowledgeEntityQueries", { enumerable: true, get: function () { return knowledge_entities_1.knowledgeEntityQueries; } });
Object.defineProperty(exports, "knowledgeEntityLinkQueries", { enumerable: true, get: function () { return knowledge_entities_1.knowledgeEntityLinkQueries; } });
var types_1 = require("./database/types");
Object.defineProperty(exports, "GOLDEN_TICKET_FIELDS", { enumerable: true, get: function () { return types_1.GOLDEN_TICKET_FIELDS; } });
Object.defineProperty(exports, "FAILURE_ATTRIBUTION_OPTIONS", { enumerable: true, get: function () { return types_1.FAILURE_ATTRIBUTION_OPTIONS; } });
// Practice Bank (v28)
var practice_bank_1 = require("./database/practice-bank");
Object.defineProperty(exports, "practiceBankQueries", { enumerable: true, get: function () { return practice_bank_1.practiceBankQueries; } });
Object.defineProperty(exports, "simulatorAttemptQueries", { enumerable: true, get: function () { return practice_bank_1.simulatorAttemptQueries; } });
var flashcard_template_engine_1 = require("./database/flashcard-template-engine");
Object.defineProperty(exports, "generateCardsForEntity", { enumerable: true, get: function () { return flashcard_template_engine_1.generateCardsForEntity; } });
Object.defineProperty(exports, "getExpectedCardCount", { enumerable: true, get: function () { return flashcard_template_engine_1.getExpectedCardCount; } });
Object.defineProperty(exports, "isEntityReadyForForging", { enumerable: true, get: function () { return flashcard_template_engine_1.isEntityReadyForForging; } });
